### ISSUE TITLE
GetBibEntryWithDOI Fails for working cite

### ISSUE THREAD

**Issue by elbamos** [ropensci/RefManageR#65]
It appears to be finding the article and then having trouble formatting it:

`RefManageR::GetBibEntryWithDOI("10.1038/sj.bjp.0707442")`

`Error in RefManageR::GetBibEntryWithDOI("10.1038/sj.bjp.0707442") :
  failed to parse the returned BibTeX results; if ‘delete.file’ is FALSE, you can try viewing and editing the file: /var/folders/s1/_v14lsc56tv44hm304m07vn40000gq/T//RtmpascYBS/file7f2772c48c3f.bib
In addition: Warning messages:
1: In do_read_bib(file, encoding = .Encoding, srcfile) :
/var/folders/s1/_v14lsc56tv44hm304m07vn40000gq/T//RtmpascYBS/file7f2772c48c3f.bib:11:88
	syntax error, unexpected TOKEN_LITERAL, expecting TOKEN_COMMA or TOKEN_RBRACE
	Dropping the entry `Pertwee_2008` (starting at line 1)
2: In do_read_bib(file, encoding = .Encoding, srcfile) :
/var/folders/s1/_v14lsc56tv44hm304m07vn40000gq/T//RtmpascYBS/file7f2772c48c3f.bib:14:0
	syntax error, unexpected $end
	Dropping the entry `Pertwee_2008` (starting at line 1)`

Any suggestions?

**Comment by mwmclean** [comment]
Thanks for the report. This no longer errors if you install the latest version of `bibtex` and `RefManageR`. There are lots of LaTeX macros in the title of this article that R doesn't know about. However, due to the new parser in `bibtex`, now `GetBibEntryWithDOI("10.1038/sj.bjp.0707442")` successfully returns a `BibEntry` object and you can edit the title field to remove the macros.
